services:
  static-server:
    image: sallysuite/sally-cdn:latest
    container_name: static-server
    ports:
      - "3001:3001"
  app:
    build: ./web-server
    image: sally-suite:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NEXTAUTH_URL: "https://localhost"
      DOMAIN_NAME: "https://localhost"
      ADMIIN_EMAILS: "admin@sallysuite.com"
      ADMIIN_PASSWORD: "admin123"
      NEXTAUTH_SECRET: SALLYFORYOU
      NEXT_PUBLIC_VERCEL_ENV: production
      POSTGRES_DATABASE: sallysuite
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passowrd01
      DATABASE_URL: postgres://postgres:passowrd01@db:5432/sallysuite
    restart: always
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passowrd01
      POSTGRES_DB: sallysuite
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-proxy/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - static-server
volumes:
  postgres_data:
